# Generated by Django 3.0.5 on 2020-04-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_death',
        ),
    ]
