# Generated by Django 3.0.5 on 2020-04-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20200411_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='id_profile',
            field=models.PositiveIntegerField(default=1, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
