# Generated by Django 3.0.5 on 2020-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20200411_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_profile',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
