# Generated by Django 3.0.5 on 2020-04-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='name_group',
        ),
    ]
