# Generated by Django 3.0.5 on 2020-04-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20200411_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(to='profile.Profile'),
        ),
    ]
