# Generated by Django 3.0.5 on 2020-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_auto_20200411_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profile.Profile'),
        ),
    ]
