# Generated by Django 3.0.5 on 2020-04-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_auto_20200411_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group',
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='groups', to='profile.Group'),
        ),
    ]
