# Generated by Django 3.0.5 on 2020-04-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20200411_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profile.Group'),
        ),
    ]
