# Generated by Django 3.0.5 on 2020-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_auto_20200412_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_Class',
            fields=[
                ('id_comp', models.AutoField(primary_key=True, serialize=False)),
                ('name_comp', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=4)),
                ('beg_hours', models.TimeField()),
                ('end_hours', models.TimeField()),
            ],
        ),
    ]
