# Generated by Django 3.0.5 on 2020-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0015_comp_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_class',
            name='price',
            field=models.IntegerField(),
        ),
    ]
