# Generated by Django 3.0.5 on 2020-04-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_auto_20200412_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comp_Class',
            new_name='CompClass',
        ),
    ]
