# Generated by Django 3.0.5 on 2020-04-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0017_auto_20200412_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compclass',
            name='name_comp',
        ),
        migrations.AddField(
            model_name='compclass',
            name='name_comp',
            field=models.ManyToManyField(blank=True, related_name='compclass', to='profile.Group'),
        ),
    ]
