# Generated by Django 3.0.6 on 2020-05-24 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('name_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id_place', models.AutoField(primary_key=True, serialize=False)),
                ('name_place', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('office', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('ph_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id_profile', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=50)),
                ('number_school', models.IntegerField()),
                ('date_of_birth', models.DateField(null=True)),
                ('ph_number', models.CharField(max_length=12)),
                ('group', models.ManyToManyField(blank=True, related_name='profiles', to='userprofile.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id_lesson', models.AutoField(primary_key=True, serialize=False)),
                ('pay', models.BooleanField(null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('name_group', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='userprofile.Group')),
                ('name_place', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='userprofile.Place')),
                ('name_teacher', models.ManyToManyField(blank=True, related_name='teacherprofile', to='userprofile.TeacherProfile')),
                ('students', models.ManyToManyField(blank=True, related_name='students', to='userprofile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CompClass',
            fields=[
                ('id_comp', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('long', models.FloatField(max_length=5)),
                ('beg_hours', models.TimeField()),
                ('end_hours', models.TimeField()),
                ('name_comp', models.ManyToManyField(blank=True, related_name='compclass', to='userprofile.Group')),
                ('name_teacher', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='userprofile.TeacherProfile')),
            ],
        ),
    ]
