# Generated by Django 3.0.6 on 2020-06-01 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('name_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id_place', models.AutoField(primary_key=True, serialize=False)),
                ('name_place', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('office', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(null=True)),
                ('ph_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id_profile', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=50)),
                ('number_school', models.IntegerField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('ph_number', models.CharField(max_length=12)),
                ('sex', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('Н', 'Не указан')], default=('Н', 'Не указан'), max_length=1)),
                ('group', models.ManyToManyField(null=True, related_name='profiles', to='userprofile.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id_statement', models.AutoField(primary_key=True, serialize=False)),
                ('pay_statement', models.FloatField(null=True)),
                ('data_statement', models.DateField(null=True)),
                ('name_group', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_statements', to='userprofile.Group')),
                ('students', models.ManyToManyField(blank=True, related_name='students_statements', to='userprofile.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CompClass',
            fields=[
                ('id_comp', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('long', models.FloatField(max_length=5)),
                ('beg_hours', models.TimeField()),
                ('end_hours', models.TimeField()),
                ('name_comp', models.ManyToManyField(blank=True, related_name='compclass', to='userprofile.Group')),
                ('name_teacher', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='userprofile.TeacherProfile')),
            ],
        ),
    ]
