# Generated by Django 3.0.6 on 2020-05-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='number_school',
            field=models.IntegerField(null=True),
        ),
    ]
