# Generated by Django 3.0.6 on 2020-06-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id_lesson', models.AutoField(primary_key=True, serialize=False)),
                ('pay', models.BooleanField(null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Group')),
                ('name_place', models.ManyToManyField(blank=True, related_name='places', to='userprofile.Place')),
                ('name_teacher', models.ManyToManyField(blank=True, related_name='teacherprofile', to='userprofile.TeacherProfile')),
                ('students', models.ManyToManyField(blank=True, related_name='students', to='userprofile.UserProfile')),
            ],
        ),
    ]
