# Generated by Django 3.0.6 on 2020-05-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200524_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='data_statement',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pay_statement',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='sex',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.ManyToManyField(null=True, related_name='profiles', to='userprofile.Group'),
        ),
    ]
