# Generated by Django 3.0.6 on 2020-05-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200525_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='data_statement',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='pay_statement',
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id_statement', models.AutoField(primary_key=True, serialize=False)),
                ('pay_statement', models.FloatField(null=True)),
                ('data_statement', models.DateField(null=True)),
                ('name_group', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_statements', to='userprofile.Group')),
                ('students', models.ManyToManyField(blank=True, related_name='students_statements', to='userprofile.UserProfile')),
            ],
        ),
    ]
