# Generated by Django 3.0.6 on 2020-05-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('name_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id_profile', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('ph_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('group', models.ManyToManyField(blank=True, related_name='profiles', to='userprofile.Group')),
            ],
        ),
        migrations.CreateModel(
            name='CompClass',
            fields=[
                ('id_comp', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('beg_hours', models.TimeField()),
                ('end_hours', models.TimeField()),
                ('name_comp', models.ManyToManyField(blank=True, related_name='compclass', to='userprofile.Group')),
            ],
        ),
    ]
