# Generated by Django 3.0.6 on 2020-05-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='userprofile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date_end',
            field=models.DateField(null=True),
        ),
    ]
