# Generated by Django 3.0.6 on 2020-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0002_auto_20200510_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id_place', models.AutoField(primary_key=True, serialize=False)),
                ('name_place', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('floor', models.IntegerField(max_length=2)),
                ('office', models.CharField(max_length=5)),
            ],
        ),
    ]
