# Generated by Django 3.0.6 on 2020-05-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0003_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('ph_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number_school',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
